### ISSUE TITLE
Placement of Skin / Hide onto Stretcher 

### ISSUE THREAD

**Issue by DarkRisenGaming** [TaskaRaine/Ancient-Tools#50]
Issue seems to be when placing Skin / Hide into the Stretcher.
If Issue checked out to be something else other then stated, please remove this Post.
______________________________________________________________________________
Running on 64 bit Windows with 64 GB RAM 
Game Version: v1.17.3 (Stable)
9/17/2022 5:33:48 PM: Critical error occurred in the following mod: ancienttools@1.4.7
Loaded Mods: weaponpacka@1.3.0, ancienttools@1.4.7, animalcages@2.0.6, autoclose@1.0.1, backpackpackplus@1.0.3, bettercrates@1.5.0, betterruins@0.0.3, blackiron@1.1.1, BuggisRandomChanges@3.1.0, cellardoor@1.3.0, composter@1.0.4, drdecor@1.0.0, fireclayfrompanning@1.0.0, harptech@0.2.1, hideandfabric@1.2.6, HumanSkinTones@0.0.3, juicyores@1.0.0, mineralinguistics@1.0.0, moredrygrass@0.2.0, moredungeons@0.1.1, leadroof@1.2.2, necessaries@1.1.3, nightwatcher@1.3.0, nomolding@2.0.1, OresAPlenty@3.0.0, pieontheshelf@1.0.0, plantmat@1.4.0, potontheshelf@1.0.0, rustandrails@1.0.3, simpleelevator@1.3.0, sortablestorage@1.5.0, translocatorengineeringredux@1.2.0, game@1.17.3, wildcraft@1.4.3, zeekea@1.6.2, egocaribautomapmarkers@2.4.0-pre.1, autosifter@1.0.1, Bettermedievalexpansion@3.8.0, calendar@1.0.0, carrycapacity@0.6.5, cosmosis@0.5.0, deathwaypoints@1.0.3, driftersounds@1.0.0, extrajuice@1.0.1, helvehammerext@1.3.1, hudclock@2.8.0, lc@1.0.0, medievalexpansion@3.8.0, morepiles@1.2.2, ruinvariants@1.0.1, smeltableingots@1.0.0, stonequarry@2.0.0-rc.2, creative@1.17.3, vsquest@0.0.4, survival@1.17.3, woodchests@1.0.3, workbenchexpansion@1.5.1, xorberax-bloodmod@0.3.2, xrowboat@0.0.5, accessibilitytweaks@3.0.2, blacksmiths@0.3.0-pre.1, carryablelogwithresin@1.0.0, onestick@1.0.1, vsvillage@0.2.4
System.NullReferenceException: Object reference not set to an instance of an object.
   at AncientTools.Utility.DisplayInventory.GenMesh(ICoreClientAPI capi, String shapePath) in C:\Projects\vsmods\mods\ancienttools\src\utility\DisplayInventory.cs:line 98
   at AncientTools.BlockEntities.BEStretchingFrame.UpdateMeshes() in C:\Projects\vsmods\mods\ancienttools\src\blockentity\BEStretchingFrame.cs:line 130
   at AncientTools.BlockEntities.BEStretchingFrame.TryPlaceHide(ItemSlot playerSlot) in C:\Projects\vsmods\mods\ancienttools\src\blockentity\BEStretchingFrame.cs:line 145
   at AncientTools.Blocks.BlockStretchingFrame.OnBlockInteractStart(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel) in C:\Projects\vsmods\mods\ancienttools\src\blocks\StretchingFrame.cs:line 136
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 890
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 536
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 199
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1176
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1364
   at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 204
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 711
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 615
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 132
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 9/6/2022 3:48:46 PM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.17.2.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 4e90

Start Time: 01d8c242bc10e314

Termination Time: 2454

Application Path: C:\Users\Jake\AppData\Roaming\Vintagestory\Vintagestory.exe

Report Id: fbdbd4b4-5be4-4e1e-9a7b-a484d42d370e

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
--------------
{ TimeGenerated = 9/3/2022 1:26:25 AM, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.17.2.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 1414

Start Time: 01d8bf0d9ebcc074

Termination Time: 45934

Application Path: C:\Users\Jake\AppData\Roaming\Vintagestory\Vintagestory.exe

Report Id: 0efe4ef6-4f16-482e-808e-517836019b54

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
--------------
{ TimeGenerated = 9/1/2022 4:48:27 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 1357930415800922428, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.1.0
P3: 10.0.22000.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\Jake\AppData\Local\Temp\RDRF38A.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.1fcadc17-f039-4801-a926-f49c404a6cc2.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.b4110616-9461-4345-bfd1-cad34cdd5435.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.6836c46f-6771-4e5b-b9f0-beb9cf863d2b.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.c2b8e3c9-a73a-495a-9501-bd3aa3a14d20.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: a55b1c98-c075-4b2d-8e40-aff1f9b62978
Report Status: 268435456
Hashed bucket: b75d27edea1e4c8de2d85684bf83313c
Cab Guid: 0 }

**Comment by TaskaRaine** [comment]
Ah, this seems to be a slight incompatibility with the Hide and Fabric mod. The stretching frame checks whether 'hide' exists as the first part of the item code and, if it does, accepts it into its inventory. With the Hide and Fabric skins, it does. The crash occurs when the stretching frame tries to display the hide because there's no shape for them. 

Fixing this shouldn't be too difficult. I'll rewrite some logic here and make it less prone to breaking like this in the future. 

Until then, probably best to avoid using the skins from Hide and Fabric on the stretching frame! 

Thanks for your detailed report. Your inclusion of a mod list and error logs made tracking down the issue very easy.

**Comment by TaskaRaine** [comment]
This update should now be resolved as of Ancient Tools V1.4.8. Thanks for the report!
