### ISSUE TITLE
crash when trying to break the Cart

### ISSUE THREAD

**Issue by RogueRaiden** [TaskaRaine/Ancient-Tools#69]
vs 1.18.6-rc.1
ancienttools 1.5.5

getting this crash when trying to break down the cart

System.NullReferenceException: Object reference not set to an instance of an object.
   at AncientTools.CollectibleBehaviors.CollectibleBehaviorMobileStorageDestruction.OnHeldInteractStart(ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handHandling, EnumHandling& handling) in C:\Projects\vsmods\mods\ancienttools\src\collectiblebehavior\CollectibleBehaviorMobileStorageDestruction.cs:line 80
   at Vintagestory.API.Common.CollectibleObject.<>c__DisplayClass98_0.<OnHeldInteractStart>b__0(CollectibleBehavior bh, EnumHandling& hd)
   at Vintagestory.API.Common.CollectibleObject.WalkBehaviors(CollectibleBehaviorDelegate onBehavior, Action defaultAction)
   at Vintagestory.API.Common.CollectibleObject.OnHeldInteractStart_Patch1(CollectibleObject this, ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handling)
   at Vintagestory.API.Common.CollectibleObject.OnHeldUseStart(ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, EnumHandInteract useType, Boolean firstEvent, EnumHandHandling& handling)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel, EnumHandInteract useType, EnumHandHandling& handling)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsNoBlockSelected(Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt)
   at Vintagestory.Client.ScreenManager.Render(Single dt)
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e)
   at OpenTK.Windowing.Desktop.GameWindow.DispatchRenderFrame()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass10_0.<.ctor>b__1()
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)

**Comment by TaskaRaine** [comment]
Oops, I used the wrong selection variable. This should be fixed in the next update- hopefully in just a few days

**Comment by TaskaRaine** [comment]
This should now be solved in Ancient Tools 1.5.6, thanks! ^_^
