### ISSUE TITLE
System.Exception: Can't create itemstack without item! when attempting to use Mortar and Pestle

### ISSUE THREAD

**Issue by fadinginterest** [TaskaRaine/Ancient-Tools#77]
Tried putting crushed cinnabar into the mortar to grind it and when i click to grind, I crash out. Here is the log. Repeated it three times.

Running on 64 bit Windows with 16306 MB RAM
Game Version: v1.18.10 (Stable)
9/18/2023 2:55:24 PM: Critical error occurred in the following mod: ancienttools@1.5.8
Loaded Mods: aculinaryartillery@1.0.15, ancienttools@1.5.8, axleinblocks@1.0.18, Ceramos@0.4.1, chiseltools@1.8.4, HangingOilLamps@1.0.1, millwright@1.0.8, leadroof@1.3.4, game@1.18.10, wildcrafttrees@1.2.4, zoombuttonreborn@1.3.0, egocaribautomapmarkers@2.6.0, carryon@1.5.0, commonlib@2.2.0, cooperativecombat@1.1.1, divisionoflabor@1.0.7, expandedfoods@1.6.7, grassiergrass@1.0.0, hudclock@3.3.0, medievalexpansion@3.10.0, morepiles@1.4.3, petai@1.8.0, prospectorinfo@3.2.0, prospecttogether@1.2.4, survivalexpanded@0.1.1, creative@1.18.10, survival@1.18.10, VsWaypointSharing@1.0.5, woodbarrels@1.0.4, em@2.3.0, feverstonewilds@1.4.2, playercorpse@1.8.0, bricklayers@2.2.0, moreroads@1.5.4
System.Exception: Can't create itemstack without item!
   at Vintagestory.API.Common.ItemStack..ctor(Item item, Int32 stacksize) in VintagestoryApi\Common\Collectible\ItemStack.cs:line 228
   at AncientTools.BlockEntities.BEMortar.SetGroundItemstack() in C:\Projects\VintageStory\Mods\ancienttools\src\blockentity\BEMortar.cs:line 458
   at AncientTools.BlockEntities.BEMortar.BeginGrind(IPlayer byPlayer) in C:\Projects\VintageStory\Mods\ancienttools\src\blockentity\BEMortar.cs:line 297
   at AncientTools.BlockEntities.BEMortar.OnSneakInteract(IPlayer byPlayer) in C:\Projects\VintageStory\Mods\ancienttools\src\blockentity\BEMortar.cs:line 287
   at AncientTools.Blocks.BlockMortar.OnBlockInteractStep(Single secondsUsed, IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel) in C:\Projects\VintageStory\Mods\ancienttools\src\blocks\Mortar.cs:line 79
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 267
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnGameTick(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 165
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 59
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 796
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 712
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 76
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 312
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by TaskaRaine** [comment]
Ah, I'm late on replying to this, my apologies.

It looks like Bricklayers and Expanded Matter has had some content shifted between mods and the outputs I use in my patches are no longer valid. I'll need to do a deep dive on this someday and figure out exactly what's been changed to fix these crashes.

**Comment by TaskaRaine** [comment]
Compatibility has presently been removed. I may look to build a companion mod for compatibility in the future.
