### ISSUE TITLE
System.ArgumentNullException: Value cannot be null. (Parameter 'Unable to find a texture for texture code 'cookedbone' in container.

### ISSUE THREAD

**Issue by WickedSchnitzel** [TaskaRaine/Ancient-Tools#86]
Getting consistent crashes on attempting insert purified bone (from 'Bricklayers') into a mortar, crash is immediate on right clicking the mortar

Running on 64 bit Linux (Linux Mint 21.2) [Kernel 5.15.0.91] with 96491 MB RAM
Game Version: v1.19.8 (Stable)
2024-07-23 5:35:58 p.m.: Critical error occurred in the following mod: ancienttools@1.5.18
Loaded Mods: aculinaryartillery@1.1.5, ancientarmory@1.0.0, bettercrates@1.7.0, explosive@0.0.2, chiseltools@1.12.3, decor@1.1.1, extrachestsfantasyedition@1.9.0, fantasycreatures@0.7.1, fixedpaths@1.0.1, pantherinae@1.1.9, foundrymod@1.0.0, mannequinstand@1.0.3, millwright@1.1.5, moreicons_cs@1.1.0, primitivesurvival@3.5.9, shinglesandthethings@1.0.2-rc.1, spyglass@0.5.1, swordz@1.1.7, translocatorengineeringredux@1.5.1, game@1.19.8, weaponpackalphaunoff@1.5.1, ancienttools@1.5.18, animalcages@3.0.2, betterfirepit@1.1.4, betterjonasdevices@1.1.0, betterruins@0.3.7, butterflycases@1.0.1, carryon@1.7.4, commonlib@2.4.0, decayingcreatures@0.0.4, expandedfoods@1.6.9, fairplayguardian@1.1.7, furniturelibrary@1.0.11, hangingbaskets@1.1.0, heatretention@1.0.2, leaderboards@1.1.6, medievalexpansion@3.13.1, morepiles@1.5.0, moreplaster@1.0.1, pelaguswinds@1.0.0, petai@2.2.5, playerlist@2.1.2, prospecttogether@1.3.0, rivers@2.7.0, sailboat@1.3.1, simplefootstepsredux@1.0.0, sleepvote@1.0.7, stonebakeoven@1.1.3, tentbag@2.1.1, th3dungeon@0.2.1, thecritterpack@0.8.9, typing_indicator@1.1.2, usefulstuff17@1.3.1, vinconomy@0.3.0, creative@1.19.8, vsinstruments@1.2.7, vsquest@1.2.0, vsserverpanel@0.1.5, survival@1.19.8, workbenchexpansion@1.8.0, xlib@0.8.6, awearablelight@1.1.1, cob2@1.6.6, em@2.6.1, outerspacetunesvolume1@1.0.2, outerspacetunesvolume2@1.0.2, playercorpse@1.10.1-rc.1, rifteye@0.3.7, stonequarry@3.3.1, vanity@2.2.0, wolftaming@2.1.2, xinvtweaks@1.6.6, xskills@0.8.8, bricklayers@2.5.4, cob@1.9.5, outerspacetunesmaster@1.0.2, vsvillagecob@0.2.0
System.ArgumentNullException: Value cannot be null. (Parameter 'Unable to find a texture for texture code 'cookedbone' in container. Giving up. Sorry.')
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElement(Int32 indexForLogging, MeshData meshdata, ShapeElement element, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 394
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(MeshData meshdata, ShapeElement[] elements, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 306
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShapeElements(MeshData meshdata, ShapeElement[] elements, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 306
   at Vintagestory.Client.NoObf.ShapeTesselator.TesselateShape(Shape shapeBase, MeshData& modeldata, Vec3f wholeMeshRotation, Vec3f wholeMeshOffset, Single wholeMeshScale, TesselationMetaData meta) in VintagestoryLib\Client\Render\Tesselation\ShapeTesselator.cs:line 302
   at AncientTools.Utility.DisplayInventory.GenMesh(JsonObject generationProperties) in C:\Projects\VintageStory\Mods\ancienttools\src\utility\BlockEntityBaseClasses\DisplayInventory.cs:line 110
   at AncientTools.BlockEntities.BEMortar.UpdateMeshes() in C:\Projects\VintageStory\Mods\ancienttools\src\blockentity\BEMortar.cs:line 513
   at AncientTools.BlockEntities.BEMortar.OnInteract(IPlayer byPlayer) in C:\Projects\VintageStory\Mods\ancienttools\src\blockentity\BEMortar.cs:line 285
   at AncientTools.Blocks.BlockMortar.OnBlockInteractStart(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel) in C:\Projects\VintageStory\Mods\ancienttools\src\blocks\Mortar.cs:line 65
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 864
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected_Patch1(SystemMouseInWorldInteractions this, Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1013
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
   
   
 Modded multiplayer, latest stable

**Comment by TaskaRaine** [comment]
Compatibility has presently been removed. I may look to build a companion mod for compatibility in the future.
